# Generated by Django 4.2 on 2023-10-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=256, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=256, verbose_name='Apellidos')),
                ('codigo', models.CharField(max_length=8, verbose_name='Codigo')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='Correo')),
                ('tipo_documento', models.CharField(max_length=10, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=10, verbose_name='Numero de documento')),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('plan', models.CharField(max_length=10, verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=256, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=256, verbose_name='Apellidos')),
                ('codigo', models.CharField(max_length=8, verbose_name='Codigo')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='Correo')),
                ('tipo_documento', models.CharField(max_length=10, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=10, verbose_name='Numero de documento')),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre')),
                ('decano', models.CharField(max_length=256, verbose_name='Datos del decano')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_imagen', models.URLField(blank=True, null=True)),
                ('url_imagen_360', models.URLField(blank=True, null=True)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('marker_url', models.URLField(blank=True, null=True)),
                ('fill_color', models.CharField(blank=True, max_length=200, null=True)),
                ('border_color', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('denominacion', models.CharField(max_length=10, verbose_name='Denominacion')),
            ],
            options={
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.curso')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.periodo')),
            ],
            options={
                'verbose_name': 'Curso Sección',
                'verbose_name_plural': 'Cursos Sección',
            },
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de lugar',
                'verbose_name_plural': 'Tipos de lugares',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_clase', models.CharField(max_length=10, verbose_name='Tipo de clase')),
                ('semana', models.PositiveIntegerField(verbose_name='Semana')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.DateTimeField(verbose_name='Hora de fin')),
                ('id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.seccion')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.CreateModel(
            name='ReservaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_solicitada_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_solicitada_fin', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.alumno')),
                ('id_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.lugar')),
            ],
            options={
                'verbose_name': 'Reserva de laboratorios',
                'verbose_name_plural': 'Reservas de laboratorios',
            },
        ),
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_solicitada_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_solicitada_fin', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.alumno')),
                ('id_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.lugar')),
            ],
            options={
                'verbose_name': 'Reserva de espacios',
                'verbose_name_plural': 'Reservas de espacios',
            },
        ),
        migrations.CreateModel(
            name='ReservaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_solicitada_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_solicitada_fin', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.lugar')),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sesion')),
            ],
            options={
                'verbose_name': 'Reserva de aula',
                'verbose_name_plural': 'Reserva de aulas',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.alumno')),
                ('id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.seccion')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.AddField(
            model_name='lugar',
            name='id_tipo_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipolugar'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='piso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.piso'),
        ),
        migrations.CreateModel(
            name='EscuelaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre')),
                ('director', models.CharField(max_length=256, verbose_name='Datos del director')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.facultad')),
            ],
            options={
                'verbose_name': 'Escuela Profesional',
                'verbose_name_plural': 'Escuelas profesionales',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='id_escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.escuelaprofesional'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.docente')),
                ('id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.seccion')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
    ]
